# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\"\n\x12HealthCheckRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x13HealthCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x11TrainModelRequest\x12\x14\n\x0c\x63onversation\x18\x01 \x03(\t\"5\n\x12TrainModelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"%\n\x12GetResponseRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x13GetResponseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32\xec\x01\n\tChatboter\x12J\n\x0b\x43heckHealth\x12\x1b.chatbot.HealthCheckRequest\x1a\x1c.chatbot.HealthCheckResponse\"\x00\x12G\n\nTrainModel\x12\x1a.chatbot.TrainModelRequest\x1a\x1b.chatbot.TrainModelResponse\"\x00\x12J\n\x0bGetResponse\x12\x1b.chatbot.GetResponseRequest\x1a\x1c.chatbot.GetResponseResponse\"\x00\x42\x31\n\x19\x63om.dumselfflydev.chatbotB\x0c\x43hatbotProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.dumselfflydev.chatbotB\014ChatbotProtoP\001\242\002\003HLW'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=26
  _globals['_HEALTHCHECKREQUEST']._serialized_end=60
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=62
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=100
  _globals['_TRAINMODELREQUEST']._serialized_start=102
  _globals['_TRAINMODELREQUEST']._serialized_end=143
  _globals['_TRAINMODELRESPONSE']._serialized_start=145
  _globals['_TRAINMODELRESPONSE']._serialized_end=198
  _globals['_GETRESPONSEREQUEST']._serialized_start=200
  _globals['_GETRESPONSEREQUEST']._serialized_end=237
  _globals['_GETRESPONSERESPONSE']._serialized_start=239
  _globals['_GETRESPONSERESPONSE']._serialized_end=293
  _globals['_CHATBOTER']._serialized_start=296
  _globals['_CHATBOTER']._serialized_end=532
# @@protoc_insertion_point(module_scope)
