# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatbot_pb2 as chatbot__pb2


class ChatboterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHealth = channel.unary_unary(
                '/chatbot.Chatboter/CheckHealth',
                request_serializer=chatbot__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=chatbot__pb2.HealthCheckResponse.FromString,
                )
        self.TrainModel = channel.unary_unary(
                '/chatbot.Chatboter/TrainModel',
                request_serializer=chatbot__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=chatbot__pb2.TrainModelResponse.FromString,
                )
        self.GetResponse = channel.unary_unary(
                '/chatbot.Chatboter/GetResponse',
                request_serializer=chatbot__pb2.GetResponseRequest.SerializeToString,
                response_deserializer=chatbot__pb2.GetResponseResponse.FromString,
                )


class ChatboterServicer(object):
    """The greeting service definition.
    """

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatboterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=chatbot__pb2.HealthCheckRequest.FromString,
                    response_serializer=chatbot__pb2.HealthCheckResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=chatbot__pb2.TrainModelRequest.FromString,
                    response_serializer=chatbot__pb2.TrainModelResponse.SerializeToString,
            ),
            'GetResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=chatbot__pb2.GetResponseRequest.FromString,
                    response_serializer=chatbot__pb2.GetResponseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.Chatboter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chatboter(object):
    """The greeting service definition.
    """

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.Chatboter/CheckHealth',
            chatbot__pb2.HealthCheckRequest.SerializeToString,
            chatbot__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.Chatboter/TrainModel',
            chatbot__pb2.TrainModelRequest.SerializeToString,
            chatbot__pb2.TrainModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.Chatboter/GetResponse',
            chatbot__pb2.GetResponseRequest.SerializeToString,
            chatbot__pb2.GetResponseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
